# Generated by Django 3.1 on 2020-08-08 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('status', models.CharField(blank=True, max_length=50)),
                ('cover', models.ImageField(default='event_covers/default.jpg', upload_to='event_covers/')),
                ('category', models.CharField(choices=[('technical', 'TECHNICAL'), ('non-technical', 'NON-TECHNICAL')], max_length=20)),
                ('rules', models.TextField()),
                ('no_of_participants', models.IntegerField()),
                ('organizers', models.TextField()),
                ('winners', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnos', models.TextField()),
                ('reg_events', models.TextField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.IntegerField()),
                ('slot_no', models.IntegerField()),
                ('datePlanned', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='events.event')),
            ],
            options={
                'unique_together': {('event', 'round_no')},
            },
        ),
    ]
